import asyncio
import logging

import pytz
from aiogram import Bot, Dispatcher, F
from aiogram.filters import Command, CommandStart
from aiogram.types import Message, ChatMemberUpdated
from aiogram.enums import ChatMemberStatus, ChatType
from apscheduler.schedulers.asyncio import AsyncIOScheduler

from config import BOT_TOKEN, BROADCAST_HOUR, BROADCAST_MINUTE, TIMEZONE
from database import init_db, add_chat, remove_chat, get_all_chats
from prayer_api import get_prayer_times, format_prayer_message

# ─── Logging sozlamalari ──────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
            datefmt="%Y-%m-%d %H:%M:%S",
            )
            logger = logging.getLogger(__name__)

            # ─── Bot va Dispatcher ────────────────────────────────────────────────────────
            bot = Bot(token=BOT_TOKEN, parse_mode="Markdown")
            dp = Dispatcher()


            # ─── /start handler ───────────────────────────────────────────────────────────
            @dp.message(CommandStart())
            async def cmd_start(message: Message):
                """Bot ishga tushganda yoki /start bosilganda chaqiriladi."""
                    chat = message.chat
                        add_chat(chat.id, chat.type, chat.title or chat.first_name)

                            if chat.type == ChatType.PRIVATE:
                                    await message.answer(
                                                "Assalomu alaykum!\n\n"
                                                            "Men har kuni soat *05:00* da namoz vaqtlarini yuboran bot.\n\n"
                                                                        "Buyruqlar:\n"
                                                                                    "/vaqtlar - bugungi namoz vaqtlari\n"
                                                                                                "/start - botni qayta ishga tushirish",
                                                                                                        )
                                                                                                            else:
                                                                                                                    await message.answer(
                                                                                                                                "Bot guruhga qo'shildi!\n"
                                                                                                                                            "Har kuni soat *05:00* da namoz vaqtlari avtomatik yuboriladi.\n"
                                                                                                                                                        "/vaqtlar - bugungi namoz vaqtlarini ko'rish",
                                                                                                                                                                )
                                                                                                                                                                    logger.info(f"/start: {chat.id} ({chat.title or chat.first_name})")
                                                                                                                                                                    
                                                                                                                                                                    
                                                                                                                                                                    # ─── /vaqtlar handler ─────────────────────────────────────────────────────────
                                                                                                                                                                    @dp.message(Command("vaqtlar"))
                                                                                                                                                                    async def cmd_vaqtlar(message: Message):
                                                                                                                                                                        """Bugungi namoz vaqtlarini ko'rsatish."""
                                                                                                                                                                            chat = message.chat
                                                                                                                                                                                add_chat(chat.id, chat.type, chat.title or chat.first_name)
                                                                                                                                                                                
                                                                                                                                                                                    wait_msg = await message.answer("Namoz vaqtlari yuklanmoqda...")
                                                                                                                                                                                    
                                                                                                                                                                                        times = await get_prayer_times()
                                                                                                                                                                                            if times:
                                                                                                                                                                                                    text = format_prayer_message(times)
                                                                                                                                                                                                            await wait_msg.edit_text(text, parse_mode="Markdown")
                                                                                                                                                                                                                else:
                                                                                                                                                                                                                        await wait_msg.edit_text(
                                                                                                                                                                                                                                    "Namoz vaqtlarini yuklab bo'lmadi. "
                                                                                                                                                                                                                                                "Iltimos, keyinroq urinib ko'ring."
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        # ─── Bot guruhga qo'shilganda / chiqarilganda ────────────────────────────────
                                                                                                                                                                                                                                                        @dp.my_chat_member()
                                                                                                                                                                                                                                                        async def on_chat_member_update(event: ChatMemberUpdated):
                                                                                                                                                                                                                                                            """Bot guruhga qo'shilganda yoki chiqarilganda ishga tushadi."""
                                                                                                                                                                                                                                                                old_status = event.old_chat_member.status
                                                                                                                                                                                                                                                                    new_status = event.new_chat_member.status
                                                                                                                                                                                                                                                                        chat = event.chat
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                            # Bot guruhga qo'shildi
                                                                                                                                                                                                                                                                                if new_status in (ChatMemberStatus.MEMBER, ChatMemberStatus.ADMINISTRATOR):
                                                                                                                                                                                                                                                                                        if old_status in (ChatMemberStatus.LEFT, ChatMemberStatus.KICKED, ChatMemberStatus.BANNED):
                                                                                                                                                                                                                                                                                                    add_chat(chat.id, chat.type, chat.title)
                                                                                                                                                                                                                                                                                                                try:
                                                                                                                                                                                                                                                                                                                                await bot.send_message(
                                                                                                                                                                                                                                                                                                                                                    chat.id,
                                                                                                                                                                                                                                                                                                                                                                        "Salom! Men namoz vaqtlarini yuboruvchi botman.\n"
                                                                                                                                                                                                                                                                                                                                                                                            "Har kuni soat *05:00* da vaqtlar yuboriladi.\n"
                                                                                                                                                                                                                                                                                                                                                                                                                "/vaqtlar - bugungi namoz vaqtlari",
                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                            except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.warning(f"Guruhga salom xabar yuborishda xato: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.info(f"Bot guruhga qo'shildi: {chat.id} ({chat.title})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Bot guruhdan chiqarildi yoki bloklandi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                elif new_status in (ChatMemberStatus.LEFT, ChatMemberStatus.KICKED, ChatMemberStatus.BANNED):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        remove_chat(chat.id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                logger.info(f"Bot guruhdan chiqarildi: {chat.id} ({chat.title})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ─── Broadcast funksiyasi ─────────────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async def broadcast_prayer_times():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Har kuni belgilangan vaqtda barcha guruhlarga namoz vaqtlarini yuboradi.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            APScheduler tomonidan chaqiriladi.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logger.info("Broadcast boshlanmoqda...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        times = await get_prayer_times()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if not times:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logger.error("Broadcast: namoz vaqtlarini yuklab bo'lmadi.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text = format_prayer_message(times)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    chats = get_all_chats()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        logger.info(f"Jami {len(chats)} ta chatga xabar yuborilmoqda...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            success, failed = 0, 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for chat_id in chats:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await bot.send_message(chat_id, text, parse_mode="Markdown")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Telegram API limitiga to'qnashmaislik uchun kichik kutish
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await asyncio.sleep(0.05)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            logger.warning(f"{chat_id} ga xabar yuborishda xato: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Agar bot guruhdan chiqarib yuborilgan bo'lsa, bazadan o'chirish
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    error_str = str(e).lower()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if any(x in error_str for x in ["bot was kicked", "chat not found",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "bot is not a member", "forbidden"]):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              remove_chat(chat_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info(f"Faol bo'lmagan chat o'chirildi: {chat_id}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          failed += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info(f"Broadcast tugadi: {success} muvaffaqiyatli, {failed} xato.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # ─── Asosiy ishga tushirish funksiyasi ───────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              async def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  """Botni ishga tushirish."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # Ma'lumotlar bazasini ishga tushirish
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          init_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Scheduler sozlash (Toshkent vaqtida)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  tz = pytz.timezone(TIMEZONE)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      scheduler = AsyncIOScheduler(timezone=tz)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          scheduler.add_job(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  broadcast_prayer_times,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          trigger="cron",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hour=BROADCAST_HOUR,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          minute=BROADCAST_MINUTE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name="namoz_vaqtlari_broadcast",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          scheduler.start()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              logger.info(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      f"Scheduler ishga tushdi: har kuni "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              f"{BROADCAST_HOUR:02d}:{BROADCAST_MINUTE:02d} da xabar yuboriladi."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # Botni ishga tushirish
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          logger.info("Bot ishga tushmoqda...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await bot.delete_webhook(drop_pending_updates=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await dp.start_polling(bot)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              finally:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      scheduler.shutdown()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await bot.session.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      logger.info("Bot to'xtatildi.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          asyncio.run(main())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
